# -*- coding: utf-8 -*-
"""Colab 시작하기의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_ouJgbYM5Ui-2P75vOv-cL8RzIWVXbr
"""

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

df = pd.read_csv('churn_logit1.csv')

model = smf.logit(
    'churn ~ age + usage_hour + complaint_cnt',
    data=df
).fit()

result = pd.DataFrame({
    'coef': model.params,
    'p_value': model.pvalues,
    'odds_ratio': np.exp(model.params)
})

print(result)

for var in ['age', 'usage_hour', 'complaint_cnt']:
    coef = model.params[var]
    pval = model.pvalues[var]
    odds = np.exp(coef)

    print()
    print("변수 :", var)
    print("계수 :", round(coef, 4))
    print("p-value :", round(pval, 6))
    print("오즈비 :", round(odds, 4))

    if pval < 0.05:
        print("유의한 변수")
    else:
        print("유의하지 않은 변수")

    if odds > 1:
        print("사건 발생 odds 증가")
    else:
        print("사건 발생 odds 감소")

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from sklearn.metrics import accuracy_score

df = pd.read_csv('loan_default_logit2.csv')

model = smf.logit(
    'default ~ income + debt_ratio + late_cnt',
    data=df
).fit()

result = pd.DataFrame({
    'coef': model.params,
    'p_value': model.pvalues,
    'odds_ratio': np.exp(model.params)
})

print(result)

llf = model.llf
residual_deviance = -2 * llf

df['pred_prob'] = model.predict(df)
df['pred_class'] = (df['pred_prob'] >= 0.5).astype(int)

accuracy = accuracy_score(
    df['default'],
    df['pred_class']
)

error_rate = 1 - accuracy

print()
print("log-likelihood :", round(llf, 4))
print("residual deviance :", round(residual_deviance, 4))
print("accuracy :", round(accuracy, 4))
print("error rate :", round(error_rate, 4))

for var in ['income', 'debt_ratio', 'late_cnt']:
    coef = model.params[var]
    pval = model.pvalues[var]
    odds = np.exp(coef)

    print()
    print("변수 :", var)
    print("계수 :", round(coef, 6))
    print("p-value :", round(pval, 6))
    print("오즈비 :", round(odds, 6))

